version: "3.9"

services:

  db:
        image: postgres
        volumes:
            - ./data/db:/var/lib/postgresql/data
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_DB=postgres
  
  redis:
      image: "redis"
      ports:
          - "6379:6379"
  
  nginx:
    build: ./nginx
    ports: 
      - "80:80"
    volumes:
      - ./library/static:/var/www/static
    depends_on:
      - web

  web:  
        build: .
        command: > 
            bash -c "python manage.py makemigrations &&
            python manage.py migrate &&
            gunicorn Library.wsgi -b 0.0.0.0:8000"
        volumes: 
            - .:/code
        ports: 
            - "8000:8000"
        environment:
            - POSTGRES_NAME=postgres
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
        depends_on:
            - db
            - redis